// Central registry of every tool the backend exposes.
// The generic ToolRunner page renders a tool purely from this config.

export type FieldType = 'text' | 'number' | 'select' | 'color' | 'textarea' | 'range';

export interface ToolField {
  name: string;
  label: string;
  type: FieldType;
  placeholder?: string;
  hint?: string;
  defaultValue?: string;
  options?: { value: string; label: string }[]; // for select
  min?: number;
  max?: number;
  step?: number;
  // Only show this field when another field has a specific value
  showWhen?: { field: string; equals: string };
}

export interface Tool {
  slug: string;
  name: string;
  shortDesc: string;
  icon: string;
  iconBg: string;
  category: 'pdf' | 'image' | 'convert' | 'ai' | 'text' | 'utils';
  endpoint: string;
  // 'single' | 'multi' | 'none' (no file — e.g. paste text)
  fileMode: 'single' | 'multi' | 'none' | 'optional';
  accept: string;
  fileFieldName: string; // multer field name: 'file' or 'files'
  minFiles?: number;
  fields: ToolField[];
  // How to handle the response
  responseType: 'download' | 'json';
  downloadName?: string;
  // For json responses that may include a `files` list (split/pdf-to-image)
  resultKind?: 'ocr' | 'language' | 'filelist' | 'generic' | 'wordcount';
  helpText?: string;
}

export const TOOLS: Tool[] = [
  // ================= PDF =================
  {
    slug: 'pdf-merge',
    name: 'Merge PDF',
    shortDesc: 'Combine multiple PDFs into one',
    icon: '🔗',
    iconBg: '#eeeefc',
    category: 'pdf',
    endpoint: '/api/pdf/merge',
    fileMode: 'multi',
    accept: '.pdf',
    fileFieldName: 'files',
    minFiles: 2,
    fields: [],
    responseType: 'download',
    downloadName: 'merged.pdf',
    helpText: 'Upload 2 or more PDF files. They will be merged in the order shown.',
  },
  {
    slug: 'pdf-split',
    name: 'Split PDF',
    shortDesc: 'Extract pages or split into files',
    icon: '✂️',
    iconBg: '#fdf3e3',
    category: 'pdf',
    endpoint: '/api/pdf/split',
    fileMode: 'single',
    accept: '.pdf',
    fileFieldName: 'file',
    fields: [
      {
        name: 'mode', label: 'Split mode', type: 'select', defaultValue: 'range',
        options: [
          { value: 'range', label: 'Page range (one PDF)' },
          { value: 'custom', label: 'Custom pages (one PDF)' },
          { value: 'every', label: 'Every page (separate PDFs)' },
        ],
      },
      { name: 'startPage', label: 'Start page', type: 'number', defaultValue: '1', min: 1, showWhen: { field: 'mode', equals: 'range' } },
      { name: 'endPage', label: 'End page', type: 'number', placeholder: 'e.g. 5', min: 1, showWhen: { field: 'mode', equals: 'range' } },
      { name: 'pages', label: 'Pages (comma separated)', type: 'text', placeholder: 'e.g. 1,3,5', showWhen: { field: 'mode', equals: 'custom' } },
    ],
    responseType: 'download',
    downloadName: 'split.pdf',
    resultKind: 'filelist',
  },
  {
    slug: 'pdf-compress',
    name: 'Compress PDF',
    shortDesc: 'Reduce PDF file size',
    icon: '🗜️',
    iconBg: '#eafaf0',
    category: 'pdf',
    endpoint: '/api/pdf/compress',
    fileMode: 'single',
    accept: '.pdf',
    fileFieldName: 'file',
    fields: [],
    responseType: 'download',
    downloadName: 'compressed.pdf',
    helpText: 'Upload a PDF, then set how much to reduce it — by percentage or a target size. Compression is best-effort and always returns the closest achievable result.',
  },
  {
    slug: 'pdf-protect',
    name: 'Protect PDF',
    shortDesc: 'Add password encryption',
    icon: '🔒',
    iconBg: '#fdeeee',
    category: 'pdf',
    endpoint: '/api/pdf/protect',
    fileMode: 'single',
    accept: '.pdf',
    fileFieldName: 'file',
    fields: [
      { name: 'password', label: 'Password', type: 'text', placeholder: 'Set a strong password' },
    ],
    responseType: 'download',
    downloadName: 'protected.pdf',
  },
  {
    slug: 'pdf-unlock',
    name: 'Unlock PDF',
    shortDesc: 'Remove password (authorized files)',
    icon: '🔓',
    iconBg: '#eefbf7',
    category: 'pdf',
    endpoint: '/api/pdf/unlock',
    fileMode: 'single',
    accept: '.pdf',
    fileFieldName: 'file',
    fields: [],
    responseType: 'download',
    downloadName: 'unlocked.pdf',
    helpText: 'Only unlock PDFs you own or are authorized to modify.',
  },
  {
    slug: 'pdf-reorder',
    name: 'Reorder Pages',
    shortDesc: 'Rearrange pages in a new order',
    icon: '🔀',
    iconBg: '#f0edfc',
    category: 'pdf',
    endpoint: '/api/pdf/reorder',
    fileMode: 'single',
    accept: '.pdf',
    fileFieldName: 'file',
    fields: [
      { name: 'orderText', label: 'New page order', type: 'text', placeholder: 'e.g. 3,1,2', hint: 'Comma separated page numbers in the new order' },
    ],
    responseType: 'download',
    downloadName: 'reordered.pdf',
  },
  {
    slug: 'pdf-rotate',
    name: 'Rotate Pages',
    shortDesc: 'Rotate all or selected pages',
    icon: '🔄',
    iconBg: '#e8f4fd',
    category: 'pdf',
    endpoint: '/api/pdf/rotate',
    fileMode: 'single',
    accept: '.pdf',
    fileFieldName: 'file',
    fields: [
      {
        name: 'angle', label: 'Rotation', type: 'select', defaultValue: '90',
        options: [
          { value: '90', label: '90° clockwise' },
          { value: '180', label: '180°' },
          { value: '270', label: '90° counter-clockwise' },
        ],
      },
      { name: 'pages', label: 'Pages', type: 'text', defaultValue: 'all', hint: '"all" or comma separated e.g. 1,3,5' },
    ],
    responseType: 'download',
    downloadName: 'rotated.pdf',
  },
  {
    slug: 'pdf-watermark',
    name: 'Add Watermark',
    shortDesc: 'Stamp text watermark on pages',
    icon: '💧',
    iconBg: '#e8f4fd',
    category: 'pdf',
    endpoint: '/api/pdf/watermark',
    fileMode: 'single',
    accept: '.pdf',
    fileFieldName: 'file',
    fields: [
      { name: 'text', label: 'Watermark text', type: 'text', defaultValue: 'CONFIDENTIAL' },
      {
        name: 'position', label: 'Position', type: 'select', defaultValue: 'center',
        options: [
          { value: 'center', label: 'Center' },
          { value: 'top-left', label: 'Top left' },
          { value: 'top-right', label: 'Top right' },
          { value: 'bottom-left', label: 'Bottom left' },
          { value: 'bottom-right', label: 'Bottom right' },
        ],
      },
      { name: 'fontSize', label: 'Font size', type: 'number', defaultValue: '60', min: 8, max: 200 },
      { name: 'opacity', label: 'Opacity (0–1)', type: 'number', defaultValue: '0.3', min: 0, max: 1, step: 0.05 },
      { name: 'color', label: 'Color', type: 'color', defaultValue: '#cccccc' },
    ],
    responseType: 'download',
    downloadName: 'watermarked.pdf',
  },
  {
    slug: 'pdf-page-numbers',
    name: 'Page Numbers',
    shortDesc: 'Add page numbers to a PDF',
    icon: '🔢',
    iconBg: '#fdf3e3',
    category: 'pdf',
    endpoint: '/api/pdf/number-pages',
    fileMode: 'single',
    accept: '.pdf',
    fileFieldName: 'file',
    fields: [
      {
        name: 'position', label: 'Position', type: 'select', defaultValue: 'bottom-center',
        options: [
          { value: 'bottom-center', label: 'Bottom center' },
          { value: 'bottom-left', label: 'Bottom left' },
          { value: 'bottom-right', label: 'Bottom right' },
          { value: 'top-center', label: 'Top center' },
          { value: 'top-left', label: 'Top left' },
          { value: 'top-right', label: 'Top right' },
        ],
      },
      {
        name: 'style', label: 'Style', type: 'select', defaultValue: 'numeric',
        options: [
          { value: 'numeric', label: '1, 2, 3…' },
          { value: 'roman', label: 'I, II, III…' },
        ],
      },
      { name: 'fontSize', label: 'Font size', type: 'number', defaultValue: '12', min: 6, max: 48 },
      { name: 'color', label: 'Color', type: 'color', defaultValue: '#000000' },
    ],
    responseType: 'download',
    downloadName: 'numbered.pdf',
  },
  {
    slug: 'pdf-edit',
    name: 'Edit PDF — Add Text',
    shortDesc: 'Write text onto PDF pages',
    icon: '✏️',
    iconBg: '#eeeefc',
    category: 'pdf',
    endpoint: '/api/pdf/add-text',
    fileMode: 'single',
    accept: '.pdf',
    fileFieldName: 'file',
    fields: [
      { name: 'text', label: 'Text to add', type: 'text', placeholder: 'Type the text to place on the page' },
      {
        name: 'position', label: 'Position', type: 'select', defaultValue: 'center',
        options: [
          { value: 'center', label: 'Center' },
          { value: 'top-left', label: 'Top left' },
          { value: 'top-center', label: 'Top center' },
          { value: 'top-right', label: 'Top right' },
          { value: 'bottom-left', label: 'Bottom left' },
          { value: 'bottom-center', label: 'Bottom center' },
          { value: 'bottom-right', label: 'Bottom right' },
        ],
      },
      { name: 'pages', label: 'Pages', type: 'text', defaultValue: 'all', hint: '"all" or comma separated e.g. 1,3,5' },
      { name: 'fontSize', label: 'Font size', type: 'number', defaultValue: '18', min: 6, max: 120 },
      { name: 'color', label: 'Color', type: 'color', defaultValue: '#000000' },
    ],
    responseType: 'download',
    downloadName: 'edited.pdf',
    helpText: 'Add custom text on top of any page — fill in labels, notes or corrections.',
  },
  {
    slug: 'pdf-delete-pages',
    name: 'Delete Pages',
    shortDesc: 'Remove unwanted pages from a PDF',
    icon: '🗑️',
    iconBg: '#fdeeee',
    category: 'pdf',
    endpoint: '/api/pdf/delete-pages',
    fileMode: 'single',
    accept: '.pdf',
    fileFieldName: 'file',
    fields: [
      { name: 'pages', label: 'Pages to delete', type: 'text', placeholder: 'e.g. 2,4,7', hint: 'Comma separated page numbers to remove' },
    ],
    responseType: 'download',
    downloadName: 'trimmed.pdf',
  },
  {
    slug: 'pdf-extract-pages',
    name: 'Extract Pages',
    shortDesc: 'Pull selected pages into a new PDF',
    icon: '📑',
    iconBg: '#eafaf0',
    category: 'pdf',
    endpoint: '/api/pdf/extract-pages',
    fileMode: 'single',
    accept: '.pdf',
    fileFieldName: 'file',
    fields: [
      { name: 'pages', label: 'Pages to extract', type: 'text', placeholder: 'e.g. 1,3,5', hint: 'Comma separated page numbers to keep' },
    ],
    responseType: 'download',
    downloadName: 'extracted.pdf',
  },
  {
    slug: 'pdf-metadata',
    name: 'Edit Metadata',
    shortDesc: 'Change title, author & keywords',
    icon: '🏷️',
    iconBg: '#fdf3e3',
    category: 'pdf',
    endpoint: '/api/pdf/metadata',
    fileMode: 'single',
    accept: '.pdf',
    fileFieldName: 'file',
    fields: [
      { name: 'title', label: 'Title', type: 'text', placeholder: 'Document title' },
      { name: 'author', label: 'Author', type: 'text', placeholder: 'Author name' },
      { name: 'subject', label: 'Subject', type: 'text', placeholder: 'Short subject line' },
      { name: 'keywords', label: 'Keywords', type: 'text', placeholder: 'comma, separated, keywords' },
    ],
    responseType: 'download',
    downloadName: 'updated.pdf',
    helpText: 'Leave a field blank to keep its current value.',
  },
  {
    slug: 'pdf-duplicate',
    name: 'Duplicate PDF',
    shortDesc: 'Repeat a document multiple times',
    icon: '📚',
    iconBg: '#e8f4fd',
    category: 'pdf',
    endpoint: '/api/pdf/duplicate',
    fileMode: 'single',
    accept: '.pdf',
    fileFieldName: 'file',
    fields: [
      { name: 'copies', label: 'Number of copies', type: 'number', defaultValue: '2', min: 2, max: 20 },
    ],
    responseType: 'download',
    downloadName: 'duplicated.pdf',
  },

  // ================= IMAGE =================
  {
    slug: 'image-compress',
    name: 'Compress Image',
    shortDesc: 'Shrink image size with quality control',
    icon: '🖼️',
    iconBg: '#eafaf0',
    category: 'image',
    endpoint: '/api/image/compress',
    fileMode: 'single',
    accept: 'image/*',
    fileFieldName: 'file',
    fields: [
      { name: 'quality', label: 'Quality (1–100)', type: 'number', defaultValue: '80', min: 1, max: 100 },
    ],
    responseType: 'download',
    downloadName: 'compressed.jpg',
  },
  {
    slug: 'image-convert',
    name: 'Convert Image',
    shortDesc: 'JPG, PNG, WEBP, BMP, TIFF',
    icon: '🎨',
    iconBg: '#f0edfc',
    category: 'image',
    endpoint: '/api/image/convert',
    fileMode: 'single',
    accept: 'image/*',
    fileFieldName: 'file',
    fields: [
      {
        name: 'format', label: 'Target format', type: 'select', defaultValue: 'png',
        options: [
          { value: 'png', label: 'PNG' },
          { value: 'jpg', label: 'JPG' },
          { value: 'webp', label: 'WEBP' },
          { value: 'bmp', label: 'BMP' },
          { value: 'tiff', label: 'TIFF' },
        ],
      },
    ],
    responseType: 'download',
    downloadName: 'converted.png',
  },
  {
    slug: 'pdf-to-image',
    name: 'PDF to Images',
    shortDesc: 'Convert each page to JPG',
    icon: '📸',
    iconBg: '#e8f4fd',
    category: 'image',
    endpoint: '/api/image/pdf-to-image',
    fileMode: 'single',
    accept: '.pdf',
    fileFieldName: 'file',
    fields: [],
    responseType: 'json',
    resultKind: 'filelist',
    helpText: 'Requires Ghostscript on the server.',
  },
  {
    slug: 'image-resize',
    name: 'Resize Image',
    shortDesc: 'Change image dimensions',
    icon: '📐',
    iconBg: '#eeeefc',
    category: 'image',
    endpoint: '/api/image/resize',
    fileMode: 'single',
    accept: 'image/*',
    fileFieldName: 'file',
    fields: [
      { name: 'width', label: 'Width (px)', type: 'number', placeholder: 'e.g. 1920', min: 1 },
      { name: 'height', label: 'Height (px)', type: 'number', placeholder: 'e.g. 1080', min: 1 },
      {
        name: 'fit', label: 'Fit mode', type: 'select', defaultValue: 'inside',
        options: [
          { value: 'inside', label: 'Fit inside (keep ratio)' },
          { value: 'cover', label: 'Cover (crop to fill)' },
          { value: 'fill', label: 'Stretch to fill' },
          { value: 'contain', label: 'Contain (pad)' },
        ],
      },
    ],
    responseType: 'download',
    downloadName: 'resized.png',
    helpText: 'Give a width, a height, or both.',
  },
  {
    slug: 'image-rotate',
    name: 'Rotate & Flip Image',
    shortDesc: 'Rotate or mirror an image',
    icon: '🔃',
    iconBg: '#fdf3e3',
    category: 'image',
    endpoint: '/api/image/rotate',
    fileMode: 'single',
    accept: 'image/*',
    fileFieldName: 'file',
    fields: [
      {
        name: 'angle', label: 'Rotation', type: 'select', defaultValue: '90',
        options: [
          { value: '0', label: 'No rotation' },
          { value: '90', label: '90° clockwise' },
          { value: '180', label: '180°' },
          { value: '270', label: '90° counter-clockwise' },
        ],
      },
      {
        name: 'flip', label: 'Flip', type: 'select', defaultValue: 'none',
        options: [
          { value: 'none', label: 'No flip' },
          { value: 'horizontal', label: 'Mirror horizontally' },
          { value: 'vertical', label: 'Mirror vertically' },
          { value: 'both', label: 'Both' },
        ],
      },
    ],
    responseType: 'download',
    downloadName: 'rotated.png',
  },
  {
    slug: 'image-crop',
    name: 'Crop Image',
    shortDesc: 'Cut out a region of an image',
    icon: '✂️',
    iconBg: '#eafaf0',
    category: 'image',
    endpoint: '/api/image/crop',
    fileMode: 'single',
    accept: 'image/*',
    fileFieldName: 'file',
    fields: [
      { name: 'left', label: 'From left (px)', type: 'number', defaultValue: '0', min: 0 },
      { name: 'top', label: 'From top (px)', type: 'number', defaultValue: '0', min: 0 },
      { name: 'width', label: 'Crop width (px)', type: 'number', placeholder: 'e.g. 500', min: 1 },
      { name: 'height', label: 'Crop height (px)', type: 'number', placeholder: 'e.g. 500', min: 1 },
    ],
    responseType: 'download',
    downloadName: 'cropped.png',
  },
  {
    slug: 'image-effects',
    name: 'Image Effects',
    shortDesc: 'Grayscale, blur, sharpen, sepia…',
    icon: '🪄',
    iconBg: '#f0edfc',
    category: 'image',
    endpoint: '/api/image/effects',
    fileMode: 'single',
    accept: 'image/*',
    fileFieldName: 'file',
    fields: [
      {
        name: 'effect', label: 'Effect', type: 'select', defaultValue: 'grayscale',
        options: [
          { value: 'grayscale', label: 'Grayscale' },
          { value: 'sepia', label: 'Sepia' },
          { value: 'blur', label: 'Blur' },
          { value: 'sharpen', label: 'Sharpen' },
          { value: 'negate', label: 'Invert colors' },
        ],
      },
      { name: 'intensity', label: 'Intensity (1–50)', type: 'number', defaultValue: '5', min: 1, max: 50, hint: 'Used for blur / sharpen' },
    ],
    responseType: 'download',
    downloadName: 'effect.png',
  },
  {
    slug: 'image-watermark',
    name: 'Watermark Image',
    shortDesc: 'Stamp text on a photo',
    icon: '💦',
    iconBg: '#e8f4fd',
    category: 'image',
    endpoint: '/api/image/watermark',
    fileMode: 'single',
    accept: 'image/*',
    fileFieldName: 'file',
    fields: [
      { name: 'text', label: 'Watermark text', type: 'text', defaultValue: '© DocZen' },
      {
        name: 'position', label: 'Position', type: 'select', defaultValue: 'center',
        options: [
          { value: 'center', label: 'Center' },
          { value: 'top-left', label: 'Top left' },
          { value: 'top-right', label: 'Top right' },
          { value: 'bottom-left', label: 'Bottom left' },
          { value: 'bottom-right', label: 'Bottom right' },
        ],
      },
      { name: 'fontSize', label: 'Font size', type: 'number', defaultValue: '48', min: 8, max: 300 },
      { name: 'opacity', label: 'Opacity (0–1)', type: 'number', defaultValue: '0.5', min: 0, max: 1, step: 0.05 },
      { name: 'color', label: 'Color', type: 'color', defaultValue: '#ffffff' },
    ],
    responseType: 'download',
    downloadName: 'watermarked.png',
  },

  // ================= CONVERT =================
  {
    slug: 'word-to-pdf',
    name: 'Word to PDF',
    shortDesc: 'Convert Word documents to PDF',
    icon: '📄',
    iconBg: '#eeeefc',
    category: 'convert',
    endpoint: '/api/convert/office-to-pdf',
    fileMode: 'single',
    accept: '.doc,.docx',
    fileFieldName: 'file',
    fields: [],
    responseType: 'download',
    downloadName: 'converted.pdf',
    helpText: 'Convert your Word document to a PDF file securely.',
  },
  {
    slug: 'pdf-to-word',
    name: 'PDF to Word',
    shortDesc: 'Convert PDF files to Word',
    icon: '📝',
    iconBg: '#eafaf0',
    category: 'convert',
    endpoint: '/api/convert/pdf-to-office', // Note: backend might need this endpoint
    fileMode: 'single',
    accept: '.pdf',
    fileFieldName: 'file',
    fields: [],
    responseType: 'download',
    downloadName: 'converted.docx',
    helpText: 'Convert your PDF to an editable Word document.',
  },
  {
    slug: 'text-to-pdf',
    name: 'Text to PDF',
    shortDesc: 'Turn a .txt file into a PDF',
    icon: '📝',
    iconBg: '#eeeefc',
    category: 'convert',
    endpoint: '/api/convert/text-to-pdf',
    fileMode: 'single',
    accept: '.txt',
    fileFieldName: 'file',
    fields: [],
    responseType: 'download',
    downloadName: 'converted.pdf',
  },
  {
    slug: 'office-to-pdf',
    name: 'Office to PDF',
    shortDesc: 'Word, Excel, PowerPoint → PDF',
    icon: '📊',
    iconBg: '#eafaf0',
    category: 'convert',
    endpoint: '/api/convert/office-to-pdf',
    fileMode: 'single',
    accept: '.doc,.docx,.xls,.xlsx,.ppt,.pptx',
    fileFieldName: 'file',
    fields: [],
    responseType: 'download',
    downloadName: 'converted.pdf',
    helpText: 'Requires LibreOffice on the server.',
  },
  {
    slug: 'html-to-pdf',
    name: 'HTML to PDF',
    shortDesc: 'Convert an HTML file to PDF',
    icon: '🌐',
    iconBg: '#fdf3e3',
    category: 'convert',
    endpoint: '/api/convert/html-to-pdf',
    fileMode: 'single',
    accept: '.html,.htm',
    fileFieldName: 'file',
    fields: [],
    responseType: 'download',
    downloadName: 'converted.pdf',
  },
  {
    slug: 'pdf-to-text',
    name: 'PDF to Text',
    shortDesc: 'Extract plain text from a PDF',
    icon: '📃',
    iconBg: '#eeeefc',
    category: 'convert',
    endpoint: '/api/convert/pdf-to-text',
    fileMode: 'single',
    accept: '.pdf',
    fileFieldName: 'file',
    fields: [],
    responseType: 'download',
    downloadName: 'extracted.txt',
  },
  {
    slug: 'word-to-text',
    name: 'Word to Text',
    shortDesc: 'Extract plain text from Word',
    icon: '📜',
    iconBg: '#eafaf0',
    category: 'convert',
    endpoint: '/api/convert/word-to-text',
    fileMode: 'single',
    accept: '.doc,.docx',
    fileFieldName: 'file',
    fields: [],
    responseType: 'download',
    downloadName: 'extracted.txt',
  },
  {
    slug: 'image-to-pdf',
    name: 'Images to PDF',
    shortDesc: 'Combine photos into one PDF',
    icon: '🖼️',
    iconBg: '#e8f4fd',
    category: 'convert',
    endpoint: '/api/convert/image-to-pdf',
    fileMode: 'multi',
    accept: 'image/*',
    fileFieldName: 'files',
    minFiles: 1,
    fields: [
      {
        name: 'pageSize', label: 'Page size', type: 'select', defaultValue: 'fit',
        options: [
          { value: 'fit', label: 'Fit to image' },
          { value: 'a4', label: 'A4 pages' },
        ],
      },
    ],
    responseType: 'download',
    downloadName: 'images.pdf',
    helpText: 'Upload one or more images — each becomes a page, in the order shown.',
  },
  {
    slug: 'markdown-to-pdf',
    name: 'Markdown to PDF',
    shortDesc: 'Render .md files as PDF',
    icon: '🗒️',
    iconBg: '#f0edfc',
    category: 'convert',
    endpoint: '/api/convert/markdown-to-pdf',
    fileMode: 'single',
    accept: '.md,.markdown,.txt',
    fileFieldName: 'file',
    fields: [],
    responseType: 'download',
    downloadName: 'converted.pdf',
    helpText: 'Headings and bullet lists are formatted; inline styling is flattened.',
  },
  {
    slug: 'excel-to-csv',
    name: 'Excel to CSV',
    shortDesc: 'Convert spreadsheets to CSV',
    icon: '📊',
    iconBg: '#eafaf0',
    category: 'convert',
    endpoint: '/api/convert/excel-to-csv',
    fileMode: 'single',
    accept: '.xls,.xlsx',
    fileFieldName: 'file',
    fields: [],
    responseType: 'download',
    downloadName: 'converted.csv',
    helpText: 'The first sheet of the workbook is exported.',
  },
  {
    slug: 'csv-to-excel',
    name: 'CSV to Excel',
    shortDesc: 'Turn CSV data into .xlsx',
    icon: '📈',
    iconBg: '#eeeefc',
    category: 'convert',
    endpoint: '/api/convert/csv-to-excel',
    fileMode: 'single',
    accept: '.csv,.txt',
    fileFieldName: 'file',
    fields: [],
    responseType: 'download',
    downloadName: 'converted.xlsx',
  },
  {
    slug: 'excel-to-pdf',
    name: 'Excel to PDF',
    shortDesc: 'Convert spreadsheets to PDF',
    icon: '📉',
    iconBg: '#fdf3e3',
    category: 'convert',
    endpoint: '/api/convert/excel-to-pdf',
    fileMode: 'single',
    accept: '.xls,.xlsx',
    fileFieldName: 'file',
    fields: [],
    responseType: 'download',
    downloadName: 'converted.pdf',
    helpText: 'All sheets are rendered as simple text tables.',
  },
  {
    slug: 'text-to-word',
    name: 'Text to Word',
    shortDesc: 'Turn a .txt file into .docx',
    icon: '📘',
    iconBg: '#e8f4fd',
    category: 'convert',
    endpoint: '/api/convert/text-to-word',
    fileMode: 'single',
    accept: '.txt,.md',
    fileFieldName: 'file',
    fields: [],
    responseType: 'download',
    downloadName: 'converted.docx',
  },

  // ================= AI / TEXT =================
  {
    slug: 'ocr',
    name: 'OCR — Extract Text',
    shortDesc: 'Read text from images & scans',
    icon: '👁️',
    iconBg: '#f0edfc',
    category: 'text',
    endpoint: '/api/ocr/extract',
    fileMode: 'single',
    accept: 'image/*,.pdf',
    fileFieldName: 'file',
    fields: [
      {
        name: 'lang', label: 'Document language', type: 'select', defaultValue: 'eng',
        options: [
          { value: 'eng', label: 'English' },
          { value: 'hin', label: 'Hindi' },
          { value: 'spa', label: 'Spanish' },
          { value: 'fra', label: 'French' },
          { value: 'deu', label: 'German' },
          { value: 'ara', label: 'Arabic' },
          { value: 'chi_sim', label: 'Chinese (Simplified)' },
        ],
      },
    ],
    responseType: 'json',
    resultKind: 'ocr',
  },
  {
    slug: 'language-detect',
    name: 'Language Detection',
    shortDesc: 'Detect language of text or files',
    icon: '🌍',
    iconBg: '#e8f4fd',
    category: 'text',
    endpoint: '/api/language/detect',
    fileMode: 'optional',
    accept: '.txt,.html,.htm,.pdf',
    fileFieldName: 'file',
    fields: [
      { name: 'text', label: 'Or paste text here', type: 'textarea', placeholder: 'Paste at least 10 characters of text…' },
    ],
    responseType: 'json',
    resultKind: 'language',
    helpText: 'Upload a TXT/HTML/PDF file, or paste text directly. Detects 180+ languages offline.',
  },

  // ================= UTILITIES =================
  {
    slug: 'qr-code',
    name: 'QR Code Generator',
    shortDesc: 'Turn any text or link into a QR code',
    icon: '🔳',
    iconBg: '#eeeefc',
    category: 'utils',
    endpoint: '/api/utils/qrcode',
    fileMode: 'none',
    accept: '',
    fileFieldName: 'file',
    fields: [
      { name: 'text', label: 'Text or URL', type: 'textarea', placeholder: 'https://example.com or any text…' },
      { name: 'size', label: 'Size (px)', type: 'number', defaultValue: '400', min: 100, max: 2000 },
      { name: 'dark', label: 'Foreground color', type: 'color', defaultValue: '#000000' },
      { name: 'light', label: 'Background color', type: 'color', defaultValue: '#ffffff' },
    ],
    responseType: 'download',
    downloadName: 'qrcode.png',
  },
  {
    slug: 'word-count',
    name: 'Word Counter',
    shortDesc: 'Words, characters & reading time',
    icon: '🔤',
    iconBg: '#eafaf0',
    category: 'utils',
    endpoint: '/api/utils/word-count',
    fileMode: 'optional',
    accept: '.txt,.md,.html,.htm',
    fileFieldName: 'file',
    fields: [
      { name: 'text', label: 'Or paste text here', type: 'textarea', placeholder: 'Paste your text…' },
    ],
    responseType: 'json',
    resultKind: 'wordcount',
  },
  {
    slug: 'text-case',
    name: 'Change Text Case',
    shortDesc: 'UPPER, lower, Title, Sentence',
    icon: '🔠',
    iconBg: '#fdf3e3',
    category: 'utils',
    endpoint: '/api/utils/text-case',
    fileMode: 'optional',
    accept: '.txt,.md',
    fileFieldName: 'file',
    fields: [
      {
        name: 'mode', label: 'Convert to', type: 'select', defaultValue: 'upper',
        options: [
          { value: 'upper', label: 'UPPERCASE' },
          { value: 'lower', label: 'lowercase' },
          { value: 'title', label: 'Title Case' },
          { value: 'sentence', label: 'Sentence case' },
        ],
      },
      { name: 'text', label: 'Or paste text here', type: 'textarea', placeholder: 'Paste your text…' },
    ],
    responseType: 'download',
    downloadName: 'transformed.txt',
  },
];

export const CATEGORIES: { key: Tool['category']; label: string; icon: string }[] = [
  { key: 'pdf', label: 'PDF Tools', icon: '📄' },
  { key: 'image', label: 'Image Tools', icon: '🖼️' },
  { key: 'convert', label: 'File Conversion', icon: '🔁' },
  { key: 'text', label: 'Text & AI', icon: '🤖' },
  { key: 'utils', label: 'Utilities', icon: '🧩' },
];

export const toolBySlug = (slug: string) => TOOLS.find((t) => t.slug === slug);
